//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hess.Corporate.GHGPortal.Web.UI.GHGPortal {
        
    public partial class GHGadmExecuteSSIS {
        
        /// <summary>
        /// lblPageTitle control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblPageTitle;
                
        /// <summary>
        /// grdVWSSISMasterController control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.GridView grdVWSSISMasterController;
        
        /// <summary>
        /// ODS_AdminConsole control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ObjectDataSource ODS_AdminConsole;
        
        /// <summary>
        /// ODS_PrevPackageRuns control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ObjectDataSource ODS_PrevPackageRuns;

        protected global::System.Web.UI.WebControls.TextBox txtStartRange;

        protected global::System.Web.UI.WebControls.TextBox txtEndRange;

        protected global::System.Web.UI.WebControls.Panel pnlSearchCriteria;

        protected global::System.Web.UI.WebControls.Panel pnlSearchBar;

        protected global::Hess.Corporate.GHGPortal.Web.UI.ExecuteSSISView ctrlExecuteSSIS;

    }
}
