//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18047.
// 
#pragma warning disable 1591

namespace Hess.Corporate.GHGPortal.Services.EnvianceTreeService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="TreeServiceSoap", Namespace="http://enviance.com/2007/TreeService")]
    public partial class TreeService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private SessionHeader sessionHeaderValueField;
        
        private System.Threading.SendOrPostCallback GetTreeOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetComplianceObjectOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSystemsOperationCompleted;
        
        private System.Threading.SendOrPostCallback CheckTagsExistOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public TreeService() {
            this.Url = global::Hess.Corporate.GHGPortal.Services.Properties.Settings.Default.GHGPortal_Services_EnvianceTreeService_TreeService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public SessionHeader SessionHeaderValue {
            get {
                return this.sessionHeaderValueField;
            }
            set {
                this.sessionHeaderValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetTreeCompletedEventHandler GetTreeCompleted;
        
        /// <remarks/>
        public event GetComplianceObjectCompletedEventHandler GetComplianceObjectCompleted;
        
        /// <remarks/>
        public event GetSystemsCompletedEventHandler GetSystemsCompleted;
        
        /// <remarks/>
        public event CheckTagsExistCompletedEventHandler CheckTagsExistCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SessionHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://enviance.com/2007/TreeService/GetTree", RequestNamespace="http://enviance.com/2007/TreeService", ResponseNamespace="http://enviance.com/2007/TreeService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ComplianceObjectInfo GetTree(string tagName, int depth) {
            object[] results = this.Invoke("GetTree", new object[] {
                        tagName,
                        depth});
            return ((ComplianceObjectInfo)(results[0]));
        }
        
        /// <remarks/>
        public void GetTreeAsync(string tagName, int depth) {
            this.GetTreeAsync(tagName, depth, null);
        }
        
        /// <remarks/>
        public void GetTreeAsync(string tagName, int depth, object userState) {
            if ((this.GetTreeOperationCompleted == null)) {
                this.GetTreeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTreeOperationCompleted);
            }
            this.InvokeAsync("GetTree", new object[] {
                        tagName,
                        depth}, this.GetTreeOperationCompleted, userState);
        }
        
        private void OnGetTreeOperationCompleted(object arg) {
            if ((this.GetTreeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTreeCompleted(this, new GetTreeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SessionHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://enviance.com/2007/TreeService/GetComplianceObject", RequestNamespace="http://enviance.com/2007/TreeService", ResponseNamespace="http://enviance.com/2007/TreeService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ComplianceObjectInfo GetComplianceObject(string tagName) {
            object[] results = this.Invoke("GetComplianceObject", new object[] {
                        tagName});
            return ((ComplianceObjectInfo)(results[0]));
        }
        
        /// <remarks/>
        public void GetComplianceObjectAsync(string tagName) {
            this.GetComplianceObjectAsync(tagName, null);
        }
        
        /// <remarks/>
        public void GetComplianceObjectAsync(string tagName, object userState) {
            if ((this.GetComplianceObjectOperationCompleted == null)) {
                this.GetComplianceObjectOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetComplianceObjectOperationCompleted);
            }
            this.InvokeAsync("GetComplianceObject", new object[] {
                        tagName}, this.GetComplianceObjectOperationCompleted, userState);
        }
        
        private void OnGetComplianceObjectOperationCompleted(object arg) {
            if ((this.GetComplianceObjectCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetComplianceObjectCompleted(this, new GetComplianceObjectCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SessionHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://enviance.com/2007/TreeService/GetSystems", RequestNamespace="http://enviance.com/2007/TreeService", ResponseNamespace="http://enviance.com/2007/TreeService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SystemInfo[] GetSystems() {
            object[] results = this.Invoke("GetSystems", new object[0]);
            return ((SystemInfo[])(results[0]));
        }
        
        /// <remarks/>
        public void GetSystemsAsync() {
            this.GetSystemsAsync(null);
        }
        
        /// <remarks/>
        public void GetSystemsAsync(object userState) {
            if ((this.GetSystemsOperationCompleted == null)) {
                this.GetSystemsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSystemsOperationCompleted);
            }
            this.InvokeAsync("GetSystems", new object[0], this.GetSystemsOperationCompleted, userState);
        }
        
        private void OnGetSystemsOperationCompleted(object arg) {
            if ((this.GetSystemsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSystemsCompleted(this, new GetSystemsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SessionHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://enviance.com/2007/TreeService/CheckTagsExist", RequestNamespace="http://enviance.com/2007/TreeService", ResponseNamespace="http://enviance.com/2007/TreeService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] CheckTagsExist(string[] objectTags) {
            object[] results = this.Invoke("CheckTagsExist", new object[] {
                        objectTags});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void CheckTagsExistAsync(string[] objectTags) {
            this.CheckTagsExistAsync(objectTags, null);
        }
        
        /// <remarks/>
        public void CheckTagsExistAsync(string[] objectTags, object userState) {
            if ((this.CheckTagsExistOperationCompleted == null)) {
                this.CheckTagsExistOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckTagsExistOperationCompleted);
            }
            this.InvokeAsync("CheckTagsExist", new object[] {
                        objectTags}, this.CheckTagsExistOperationCompleted, userState);
        }
        
        private void OnCheckTagsExistOperationCompleted(object arg) {
            if ((this.CheckTagsExistCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckTagsExistCompleted(this, new CheckTagsExistCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18047")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://enviance.com/Security")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://enviance.com/2007/TreeService", IsNullable=false)]
    public partial class SessionHeader : System.Web.Services.Protocols.SoapHeader {
        
        private System.Guid sessionIDField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public System.Guid SessionID {
            get {
                return this.sessionIDField;
            }
            set {
                this.sessionIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18047")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://enviance.com/2007/TreeService")]
    public partial class SystemInfo {
        
        private System.Guid idField;
        
        private string nameField;
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public System.Guid ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18047")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://enviance.com/2007/TreeService")]
    public partial class HyperLink {
        
        private string labelField;
        
        private string uRLField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string URL {
            get {
                return this.uRLField;
            }
            set {
                this.uRLField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LinkedOption))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18047")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://enviance.com/2007/TreeService")]
    public partial class Option {
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18047")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://enviance.com/2007/TreeService")]
    public partial class LinkedOption : Option {
        
        private LinkedOption option1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Option")]
        public LinkedOption Option1 {
            get {
                return this.option1Field;
            }
            set {
                this.option1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18047")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://enviance.com/2007/TreeService")]
    public partial class RootOption {
        
        private LinkedOption optionField;
        
        /// <remarks/>
        public LinkedOption Option {
            get {
                return this.optionField;
            }
            set {
                this.optionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CustomFieldBasicValue))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CustomFieldMultiValue))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CustomFieldHyperLinkValue))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CustomFieldLinkedValue))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18047")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://enviance.com/2007/TreeService")]
    public partial class CustomFieldInfo {
        
        private string nameField;
        
        private UdfType typeField;
        
        private string beginDateField;
        
        private string endDateField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public UdfType Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string BeginDate {
            get {
                return this.beginDateField;
            }
            set {
                this.beginDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string EndDate {
            get {
                return this.endDateField;
            }
            set {
                this.endDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18047")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://enviance.com/2007/TreeService")]
    public enum UdfType {
        
        /// <remarks/>
        Undefined,
        
        /// <remarks/>
        Text,
        
        /// <remarks/>
        Float,
        
        /// <remarks/>
        Datetime,
        
        /// <remarks/>
        Boolean,
        
        /// <remarks/>
        Formula,
        
        /// <remarks/>
        Hyperlink,
        
        /// <remarks/>
        CitationHyperlink,
        
        /// <remarks/>
        UniqueTag,
        
        /// <remarks/>
        Label,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18047")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://enviance.com/2007/TreeService")]
    public partial class CustomFieldBasicValue : CustomFieldInfo {
        
        private string valueField;
        
        /// <remarks/>
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18047")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://enviance.com/2007/TreeService")]
    public partial class CustomFieldMultiValue : CustomFieldInfo {
        
        private Option[] valueField;
        
        /// <remarks/>
        public Option[] Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18047")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://enviance.com/2007/TreeService")]
    public partial class CustomFieldHyperLinkValue : CustomFieldInfo {
        
        private HyperLink valueField;
        
        /// <remarks/>
        public HyperLink Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18047")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://enviance.com/2007/TreeService")]
    public partial class CustomFieldLinkedValue : CustomFieldInfo {
        
        private RootOption valueField;
        
        /// <remarks/>
        public RootOption Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RequirementInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(NumericRequirementInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FacilityInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UnitInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(POIInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EventLogInfo))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18047")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://enviance.com/2007/TreeService")]
    public partial class ComplianceObjectInfo {
        
        private string tagField;
        
        private string nameField;
        
        private string parentTagField;
        
        private string typeField;
        
        private CustomFieldInfo[] customFieldsField;
        
        private ComplianceObjectInfo[] childrenField;
        
        private bool leafField;
        
        private System.Xml.XmlElement[] anyField;
        
        private string createDateField;
        
        private string activateDateField;
        
        private string deactivateDateField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public string Tag {
            get {
                return this.tagField;
            }
            set {
                this.tagField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string ParentTag {
            get {
                return this.parentTagField;
            }
            set {
                this.parentTagField = value;
            }
        }
        
        /// <remarks/>
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public CustomFieldInfo[] CustomFields {
            get {
                return this.customFieldsField;
            }
            set {
                this.customFieldsField = value;
            }
        }
        
        /// <remarks/>
        public ComplianceObjectInfo[] Children {
            get {
                return this.childrenField;
            }
            set {
                this.childrenField = value;
            }
        }
        
        /// <remarks/>
        public bool Leaf {
            get {
                return this.leafField;
            }
            set {
                this.leafField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CreateDate {
            get {
                return this.createDateField;
            }
            set {
                this.createDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ActivateDate {
            get {
                return this.activateDateField;
            }
            set {
                this.activateDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DeactivateDate {
            get {
                return this.deactivateDateField;
            }
            set {
                this.deactivateDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(NumericRequirementInfo))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18047")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://enviance.com/2007/TreeService")]
    public partial class RequirementInfo : ComplianceObjectInfo {
        
        private string requirementTypeField;
        
        private string descriptionField;
        
        private int periodFrequencyField;
        
        private string periodTimeField;
        
        private string title3Field;
        
        /// <remarks/>
        public string RequirementType {
            get {
                return this.requirementTypeField;
            }
            set {
                this.requirementTypeField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public int PeriodFrequency {
            get {
                return this.periodFrequencyField;
            }
            set {
                this.periodFrequencyField = value;
            }
        }
        
        /// <remarks/>
        public string PeriodTime {
            get {
                return this.periodTimeField;
            }
            set {
                this.periodTimeField = value;
            }
        }
        
        /// <remarks/>
        public string Title3 {
            get {
                return this.title3Field;
            }
            set {
                this.title3Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18047")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://enviance.com/2007/TreeService")]
    public partial class NumericRequirementInfo : RequirementInfo {
        
        private string uOMField;
        
        private int precisionField;
        
        /// <remarks/>
        public string UOM {
            get {
                return this.uOMField;
            }
            set {
                this.uOMField = value;
            }
        }
        
        /// <remarks/>
        public int Precision {
            get {
                return this.precisionField;
            }
            set {
                this.precisionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18047")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://enviance.com/2007/TreeService")]
    public partial class FacilityInfo : ComplianceObjectInfo {
        
        private string companyField;
        
        private string titleField;
        
        private string contactFirstNameField;
        
        private string contactLastNameField;
        
        private string siteNameField;
        
        private string siteAddressField;
        
        private string siteCityField;
        
        private string siteCountryField;
        
        private string siteStateField;
        
        private string siteCountyField;
        
        private string sitePostalCodeField;
        
        private string mailAddressField;
        
        private string mailCityField;
        
        private string mailCountryField;
        
        private string mailStateField;
        
        private string mailPostalCodeField;
        
        private string telNoField;
        
        private string faxNoField;
        
        private string mobileField;
        
        private string emailField;
        
        private string dunBradNoField;
        
        private string sIC1Field;
        
        private string sIC2Field;
        
        private string rCRAField;
        
        private string otherAddressField;
        
        /// <remarks/>
        public string Company {
            get {
                return this.companyField;
            }
            set {
                this.companyField = value;
            }
        }
        
        /// <remarks/>
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        public string ContactFirstName {
            get {
                return this.contactFirstNameField;
            }
            set {
                this.contactFirstNameField = value;
            }
        }
        
        /// <remarks/>
        public string ContactLastName {
            get {
                return this.contactLastNameField;
            }
            set {
                this.contactLastNameField = value;
            }
        }
        
        /// <remarks/>
        public string SiteName {
            get {
                return this.siteNameField;
            }
            set {
                this.siteNameField = value;
            }
        }
        
        /// <remarks/>
        public string SiteAddress {
            get {
                return this.siteAddressField;
            }
            set {
                this.siteAddressField = value;
            }
        }
        
        /// <remarks/>
        public string SiteCity {
            get {
                return this.siteCityField;
            }
            set {
                this.siteCityField = value;
            }
        }
        
        /// <remarks/>
        public string SiteCountry {
            get {
                return this.siteCountryField;
            }
            set {
                this.siteCountryField = value;
            }
        }
        
        /// <remarks/>
        public string SiteState {
            get {
                return this.siteStateField;
            }
            set {
                this.siteStateField = value;
            }
        }
        
        /// <remarks/>
        public string SiteCounty {
            get {
                return this.siteCountyField;
            }
            set {
                this.siteCountyField = value;
            }
        }
        
        /// <remarks/>
        public string SitePostalCode {
            get {
                return this.sitePostalCodeField;
            }
            set {
                this.sitePostalCodeField = value;
            }
        }
        
        /// <remarks/>
        public string MailAddress {
            get {
                return this.mailAddressField;
            }
            set {
                this.mailAddressField = value;
            }
        }
        
        /// <remarks/>
        public string MailCity {
            get {
                return this.mailCityField;
            }
            set {
                this.mailCityField = value;
            }
        }
        
        /// <remarks/>
        public string MailCountry {
            get {
                return this.mailCountryField;
            }
            set {
                this.mailCountryField = value;
            }
        }
        
        /// <remarks/>
        public string MailState {
            get {
                return this.mailStateField;
            }
            set {
                this.mailStateField = value;
            }
        }
        
        /// <remarks/>
        public string MailPostalCode {
            get {
                return this.mailPostalCodeField;
            }
            set {
                this.mailPostalCodeField = value;
            }
        }
        
        /// <remarks/>
        public string TelNo {
            get {
                return this.telNoField;
            }
            set {
                this.telNoField = value;
            }
        }
        
        /// <remarks/>
        public string FaxNo {
            get {
                return this.faxNoField;
            }
            set {
                this.faxNoField = value;
            }
        }
        
        /// <remarks/>
        public string Mobile {
            get {
                return this.mobileField;
            }
            set {
                this.mobileField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string DunBradNo {
            get {
                return this.dunBradNoField;
            }
            set {
                this.dunBradNoField = value;
            }
        }
        
        /// <remarks/>
        public string SIC1 {
            get {
                return this.sIC1Field;
            }
            set {
                this.sIC1Field = value;
            }
        }
        
        /// <remarks/>
        public string SIC2 {
            get {
                return this.sIC2Field;
            }
            set {
                this.sIC2Field = value;
            }
        }
        
        /// <remarks/>
        public string RCRA {
            get {
                return this.rCRAField;
            }
            set {
                this.rCRAField = value;
            }
        }
        
        /// <remarks/>
        public string OtherAddress {
            get {
                return this.otherAddressField;
            }
            set {
                this.otherAddressField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18047")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://enviance.com/2007/TreeService")]
    public partial class UnitInfo : ComplianceObjectInfo {
        
        private string descriptionField;
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18047")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://enviance.com/2007/TreeService")]
    public partial class POIInfo : ComplianceObjectInfo {
        
        private string descriptionField;
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18047")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://enviance.com/2007/TreeService")]
    public partial class EventLogInfo : ComplianceObjectInfo {
        
        private string descriptionField;
        
        private string dataEntryTypeField;
        
        private string limitTypeField;
        
        private string trackNonNumericField;
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string DataEntryType {
            get {
                return this.dataEntryTypeField;
            }
            set {
                this.dataEntryTypeField = value;
            }
        }
        
        /// <remarks/>
        public string LimitType {
            get {
                return this.limitTypeField;
            }
            set {
                this.limitTypeField = value;
            }
        }
        
        /// <remarks/>
        public string TrackNonNumeric {
            get {
                return this.trackNonNumericField;
            }
            set {
                this.trackNonNumericField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetTreeCompletedEventHandler(object sender, GetTreeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTreeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTreeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ComplianceObjectInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ComplianceObjectInfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetComplianceObjectCompletedEventHandler(object sender, GetComplianceObjectCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetComplianceObjectCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetComplianceObjectCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ComplianceObjectInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ComplianceObjectInfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetSystemsCompletedEventHandler(object sender, GetSystemsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSystemsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSystemsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SystemInfo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SystemInfo[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void CheckTagsExistCompletedEventHandler(object sender, CheckTagsExistCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckTagsExistCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckTagsExistCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591