//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18047.
// 
#pragma warning disable 1591

namespace Hess.Corporate.GHGPortal.Services.EnvianceDataSubmissionService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="DataServiceSoap", Namespace="http://enviance.com/2010/DataService")]
    public partial class DataService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private SessionHeader sessionHeaderValueField;
        
        private System.Threading.SendOrPostCallback SubmitNumericDataBatchOperationCompleted;
        
        private System.Threading.SendOrPostCallback SubmitNonNumericDataBatchOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetBatchStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetBatchStatusesByDateRangeOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetInvalidBatchDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteNumericDataOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public DataService() {
            this.Url = global::Hess.Corporate.GHGPortal.Services.Properties.Settings.Default.GHGPortal_Services_EnvianceDataService_DataService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public SessionHeader SessionHeaderValue {
            get {
                return this.sessionHeaderValueField;
            }
            set {
                this.sessionHeaderValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SubmitNumericDataBatchCompletedEventHandler SubmitNumericDataBatchCompleted;
        
        /// <remarks/>
        public event SubmitNonNumericDataBatchCompletedEventHandler SubmitNonNumericDataBatchCompleted;
        
        /// <remarks/>
        public event GetBatchStatusCompletedEventHandler GetBatchStatusCompleted;
        
        /// <remarks/>
        public event GetBatchStatusesByDateRangeCompletedEventHandler GetBatchStatusesByDateRangeCompleted;
        
        /// <remarks/>
        public event GetInvalidBatchDataCompletedEventHandler GetInvalidBatchDataCompleted;
        
        /// <remarks/>
        public event DeleteNumericDataCompletedEventHandler DeleteNumericDataCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SessionHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://enviance.com/2010/DataService/SubmitNumericDataBatch", RequestNamespace="http://enviance.com/2010/DataService", ResponseNamespace="http://enviance.com/2010/DataService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Guid SubmitNumericDataBatch(DataPoint[] batch, bool partialProcess, bool autoResubmit) {
            object[] results = this.Invoke("SubmitNumericDataBatch", new object[] {
                        batch,
                        partialProcess,
                        autoResubmit});
            return ((System.Guid)(results[0]));
        }
        
        /// <remarks/>
        public void SubmitNumericDataBatchAsync(DataPoint[] batch, bool partialProcess, bool autoResubmit) {
            this.SubmitNumericDataBatchAsync(batch, partialProcess, autoResubmit, null);
        }
        
        /// <remarks/>
        public void SubmitNumericDataBatchAsync(DataPoint[] batch, bool partialProcess, bool autoResubmit, object userState) {
            if ((this.SubmitNumericDataBatchOperationCompleted == null)) {
                this.SubmitNumericDataBatchOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSubmitNumericDataBatchOperationCompleted);
            }
            this.InvokeAsync("SubmitNumericDataBatch", new object[] {
                        batch,
                        partialProcess,
                        autoResubmit}, this.SubmitNumericDataBatchOperationCompleted, userState);
        }
        
        private void OnSubmitNumericDataBatchOperationCompleted(object arg) {
            if ((this.SubmitNumericDataBatchCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SubmitNumericDataBatchCompleted(this, new SubmitNumericDataBatchCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SessionHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://enviance.com/2010/DataService/SubmitNonNumericDataBatch", RequestNamespace="http://enviance.com/2010/DataService", ResponseNamespace="http://enviance.com/2010/DataService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Guid SubmitNonNumericDataBatch(NonNumericDataPoint[] batch, bool partialProcess, bool autoResubmit) {
            object[] results = this.Invoke("SubmitNonNumericDataBatch", new object[] {
                        batch,
                        partialProcess,
                        autoResubmit});
            return ((System.Guid)(results[0]));
        }
        
        /// <remarks/>
        public void SubmitNonNumericDataBatchAsync(NonNumericDataPoint[] batch, bool partialProcess, bool autoResubmit) {
            this.SubmitNonNumericDataBatchAsync(batch, partialProcess, autoResubmit, null);
        }
        
        /// <remarks/>
        public void SubmitNonNumericDataBatchAsync(NonNumericDataPoint[] batch, bool partialProcess, bool autoResubmit, object userState) {
            if ((this.SubmitNonNumericDataBatchOperationCompleted == null)) {
                this.SubmitNonNumericDataBatchOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSubmitNonNumericDataBatchOperationCompleted);
            }
            this.InvokeAsync("SubmitNonNumericDataBatch", new object[] {
                        batch,
                        partialProcess,
                        autoResubmit}, this.SubmitNonNumericDataBatchOperationCompleted, userState);
        }
        
        private void OnSubmitNonNumericDataBatchOperationCompleted(object arg) {
            if ((this.SubmitNonNumericDataBatchCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SubmitNonNumericDataBatchCompleted(this, new SubmitNonNumericDataBatchCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SessionHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://enviance.com/2010/DataService/GetBatchStatus", RequestNamespace="http://enviance.com/2010/DataService", ResponseNamespace="http://enviance.com/2010/DataService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public BatchStatus GetBatchStatus(System.Guid batchID) {
            object[] results = this.Invoke("GetBatchStatus", new object[] {
                        batchID});
            return ((BatchStatus)(results[0]));
        }
        
        /// <remarks/>
        public void GetBatchStatusAsync(System.Guid batchID) {
            this.GetBatchStatusAsync(batchID, null);
        }
        
        /// <remarks/>
        public void GetBatchStatusAsync(System.Guid batchID, object userState) {
            if ((this.GetBatchStatusOperationCompleted == null)) {
                this.GetBatchStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetBatchStatusOperationCompleted);
            }
            this.InvokeAsync("GetBatchStatus", new object[] {
                        batchID}, this.GetBatchStatusOperationCompleted, userState);
        }
        
        private void OnGetBatchStatusOperationCompleted(object arg) {
            if ((this.GetBatchStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetBatchStatusCompleted(this, new GetBatchStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SessionHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://enviance.com/2010/DataService/GetBatchStatusesByDateRange", RequestNamespace="http://enviance.com/2010/DataService", ResponseNamespace="http://enviance.com/2010/DataService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public BatchStatus[] GetBatchStatusesByDateRange(System.DateTime beginDate, System.DateTime endDate) {
            object[] results = this.Invoke("GetBatchStatusesByDateRange", new object[] {
                        beginDate,
                        endDate});
            return ((BatchStatus[])(results[0]));
        }
        
        /// <remarks/>
        public void GetBatchStatusesByDateRangeAsync(System.DateTime beginDate, System.DateTime endDate) {
            this.GetBatchStatusesByDateRangeAsync(beginDate, endDate, null);
        }
        
        /// <remarks/>
        public void GetBatchStatusesByDateRangeAsync(System.DateTime beginDate, System.DateTime endDate, object userState) {
            if ((this.GetBatchStatusesByDateRangeOperationCompleted == null)) {
                this.GetBatchStatusesByDateRangeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetBatchStatusesByDateRangeOperationCompleted);
            }
            this.InvokeAsync("GetBatchStatusesByDateRange", new object[] {
                        beginDate,
                        endDate}, this.GetBatchStatusesByDateRangeOperationCompleted, userState);
        }
        
        private void OnGetBatchStatusesByDateRangeOperationCompleted(object arg) {
            if ((this.GetBatchStatusesByDateRangeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetBatchStatusesByDateRangeCompleted(this, new GetBatchStatusesByDateRangeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SessionHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://enviance.com/2010/DataService/GetInvalidBatchData", RequestNamespace="http://enviance.com/2010/DataService", ResponseNamespace="http://enviance.com/2010/DataService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public InvalidBatchData[] GetInvalidBatchData(System.Guid batchID) {
            object[] results = this.Invoke("GetInvalidBatchData", new object[] {
                        batchID});
            return ((InvalidBatchData[])(results[0]));
        }
        
        /// <remarks/>
        public void GetInvalidBatchDataAsync(System.Guid batchID) {
            this.GetInvalidBatchDataAsync(batchID, null);
        }
        
        /// <remarks/>
        public void GetInvalidBatchDataAsync(System.Guid batchID, object userState) {
            if ((this.GetInvalidBatchDataOperationCompleted == null)) {
                this.GetInvalidBatchDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetInvalidBatchDataOperationCompleted);
            }
            this.InvokeAsync("GetInvalidBatchData", new object[] {
                        batchID}, this.GetInvalidBatchDataOperationCompleted, userState);
        }
        
        private void OnGetInvalidBatchDataOperationCompleted(object arg) {
            if ((this.GetInvalidBatchDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetInvalidBatchDataCompleted(this, new GetInvalidBatchDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SessionHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://enviance.com/2010/DataService/DeleteNumericData", RequestNamespace="http://enviance.com/2010/DataService", ResponseNamespace="http://enviance.com/2010/DataService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Guid DeleteNumericData(RequirementsRange[] batch) {
            object[] results = this.Invoke("DeleteNumericData", new object[] {
                        batch});
            return ((System.Guid)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteNumericDataAsync(RequirementsRange[] batch) {
            this.DeleteNumericDataAsync(batch, null);
        }
        
        /// <remarks/>
        public void DeleteNumericDataAsync(RequirementsRange[] batch, object userState) {
            if ((this.DeleteNumericDataOperationCompleted == null)) {
                this.DeleteNumericDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteNumericDataOperationCompleted);
            }
            this.InvokeAsync("DeleteNumericData", new object[] {
                        batch}, this.DeleteNumericDataOperationCompleted, userState);
        }
        
        private void OnDeleteNumericDataOperationCompleted(object arg) {
            if ((this.DeleteNumericDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteNumericDataCompleted(this, new DeleteNumericDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18047")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://enviance.com/Security")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://enviance.com/2010/DataService", IsNullable=false)]
    public partial class SessionHeader : System.Web.Services.Protocols.SoapHeader {
        
        private System.Guid sessionIDField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public System.Guid SessionID {
            get {
                return this.sessionIDField;
            }
            set {
                this.sessionIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18047")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://enviance.com/2010/DataService")]
    public partial class RequirementsRange {
        
        private EnvianceID requirementIdField;
        
        private System.Nullable<System.DateTime> beginDateField;
        
        private System.Nullable<System.DateTime> endDateField;
        
        /// <remarks/>
        public EnvianceID RequirementId {
            get {
                return this.requirementIdField;
            }
            set {
                this.requirementIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> BeginDate {
            get {
                return this.beginDateField;
            }
            set {
                this.beginDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> EndDate {
            get {
                return this.endDateField;
            }
            set {
                this.endDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GuidID))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(NameId))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TagID))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PathId))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18047")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://enviance.com/2010/DataService")]
    public abstract partial class EnvianceID {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18047")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://enviance.com/2010/DataService")]
    public partial class GuidID : EnvianceID {
        
        private System.Guid idField;
        
        /// <remarks/>
        public System.Guid ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18047")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://enviance.com/2010/DataService")]
    public partial class NameId : EnvianceID {
        
        private string nameField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18047")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://enviance.com/2010/DataService")]
    public partial class TagID : EnvianceID {
        
        private string tagField;
        
        /// <remarks/>
        public string Tag {
            get {
                return this.tagField;
            }
            set {
                this.tagField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18047")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://enviance.com/2010/DataService")]
    public partial class PathId : EnvianceID {
        
        private string pathField;
        
        /// <remarks/>
        public string Path {
            get {
                return this.pathField;
            }
            set {
                this.pathField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(NumericDataPointValues))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18047")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://enviance.com/2010/DataService")]
    public abstract partial class DataValues {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18047")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://enviance.com/2010/DataService")]
    public partial class NumericDataPointValues : DataValues {
        
        private string tagField;
        
        private System.DateTime completeDateField;
        
        private double valueField;
        
        /// <remarks/>
        public string Tag {
            get {
                return this.tagField;
            }
            set {
                this.tagField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime CompleteDate {
            get {
                return this.completeDateField;
            }
            set {
                this.completeDateField = value;
            }
        }
        
        /// <remarks/>
        public double Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18047")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://enviance.com/2010/DataService")]
    public partial class InvalidBatchData {
        
        private System.Guid batchIDField;
        
        private CommandDataType dataTypeField;
        
        private DataValues dataDetailsField;
        
        private string errorField;
        
        /// <remarks/>
        public System.Guid BatchID {
            get {
                return this.batchIDField;
            }
            set {
                this.batchIDField = value;
            }
        }
        
        /// <remarks/>
        public CommandDataType DataType {
            get {
                return this.dataTypeField;
            }
            set {
                this.dataTypeField = value;
            }
        }
        
        /// <remarks/>
        public DataValues DataDetails {
            get {
                return this.dataDetailsField;
            }
            set {
                this.dataDetailsField = value;
            }
        }
        
        /// <remarks/>
        public string Error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18047")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://enviance.com/2010/DataService")]
    public enum CommandDataType {
        
        /// <remarks/>
        NumericDataPoint,
        
        /// <remarks/>
        NonNumericDataPoint,
        
        /// <remarks/>
        WorkflowInstance,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18047")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://enviance.com/2010/DataService")]
    public partial class BatchStatus {
        
        private System.Guid idField;
        
        private CommandStatusCode statusCodeField;
        
        private CommandProcessMode processModeField;
        
        private System.DateTime issuedDateField;
        
        private System.DateTime startedProcessingDateField;
        
        private System.DateTime finishedProcessingDateField;
        
        private string errorMessageField;
        
        private int errorCountField;
        
        /// <remarks/>
        public System.Guid ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public CommandStatusCode StatusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
            }
        }
        
        /// <remarks/>
        public CommandProcessMode ProcessMode {
            get {
                return this.processModeField;
            }
            set {
                this.processModeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime IssuedDate {
            get {
                return this.issuedDateField;
            }
            set {
                this.issuedDateField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime StartedProcessingDate {
            get {
                return this.startedProcessingDateField;
            }
            set {
                this.startedProcessingDateField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime FinishedProcessingDate {
            get {
                return this.finishedProcessingDateField;
            }
            set {
                this.finishedProcessingDateField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
        
        /// <remarks/>
        public int ErrorCount {
            get {
                return this.errorCountField;
            }
            set {
                this.errorCountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18047")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://enviance.com/2010/DataService")]
    public enum CommandStatusCode {
        
        /// <remarks/>
        Waiting,
        
        /// <remarks/>
        Processing,
        
        /// <remarks/>
        Succeeded,
        
        /// <remarks/>
        Failed,
        
        /// <remarks/>
        Resubmitted,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18047")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://enviance.com/2010/DataService")]
    public enum CommandProcessMode {
        
        /// <remarks/>
        Full,
        
        /// <remarks/>
        Partial,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18047")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://enviance.com/2010/DataService")]
    public partial class NonNumericDataPoint {
        
        private EnvianceID requirementIdField;
        
        private string collectorField;
        
        private ComplyState complyField;
        
        private string commentsField;
        
        private System.DateTime completeDateField;
        
        private System.DateTime complianceBeginField;
        
        private System.DateTime complianceEndField;
        
        /// <remarks/>
        public EnvianceID RequirementId {
            get {
                return this.requirementIdField;
            }
            set {
                this.requirementIdField = value;
            }
        }
        
        /// <remarks/>
        public string Collector {
            get {
                return this.collectorField;
            }
            set {
                this.collectorField = value;
            }
        }
        
        /// <remarks/>
        public ComplyState Comply {
            get {
                return this.complyField;
            }
            set {
                this.complyField = value;
            }
        }
        
        /// <remarks/>
        public string Comments {
            get {
                return this.commentsField;
            }
            set {
                this.commentsField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime CompleteDate {
            get {
                return this.completeDateField;
            }
            set {
                this.completeDateField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ComplianceBegin {
            get {
                return this.complianceBeginField;
            }
            set {
                this.complianceBeginField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ComplianceEnd {
            get {
                return this.complianceEndField;
            }
            set {
                this.complianceEndField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18047")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://enviance.com/2010/DataService")]
    public enum ComplyState {
        
        /// <remarks/>
        YesWithComments,
        
        /// <remarks/>
        Yes,
        
        /// <remarks/>
        NotDetermined,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18047")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://enviance.com/2010/DataService")]
    public partial class ValueItem {
        
        private ValueItem valueItemLinkField;
        
        private string valueField;
        
        /// <remarks/>
        public ValueItem ValueItemLink {
            get {
                return this.valueItemLinkField;
            }
            set {
                this.valueItemLinkField = value;
            }
        }
        
        /// <remarks/>
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18047")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://enviance.com/2010/DataService")]
    public partial class QualityData {
        
        private ValueItem valueItemField;
        
        private EnvianceID udfIdField;
        
        /// <remarks/>
        public ValueItem ValueItem {
            get {
                return this.valueItemField;
            }
            set {
                this.valueItemField = value;
            }
        }
        
        /// <remarks/>
        public EnvianceID UdfId {
            get {
                return this.udfIdField;
            }
            set {
                this.udfIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18047")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://enviance.com/2010/DataService")]
    public partial class DataPoint {
        
        private QualityData[] qualityDataField;
        
        private EnvianceID requirementIdField;
        
        private string collectorField;
        
        private double valueField;
        
        private System.DateTime completeField;
        
        /// <remarks/>
        public QualityData[] QualityData {
            get {
                return this.qualityDataField;
            }
            set {
                this.qualityDataField = value;
            }
        }
        
        /// <remarks/>
        public EnvianceID RequirementId {
            get {
                return this.requirementIdField;
            }
            set {
                this.requirementIdField = value;
            }
        }
        
        /// <remarks/>
        public string Collector {
            get {
                return this.collectorField;
            }
            set {
                this.collectorField = value;
            }
        }
        
        /// <remarks/>
        public double Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Complete {
            get {
                return this.completeField;
            }
            set {
                this.completeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void SubmitNumericDataBatchCompletedEventHandler(object sender, SubmitNumericDataBatchCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SubmitNumericDataBatchCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SubmitNumericDataBatchCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Guid Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Guid)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void SubmitNonNumericDataBatchCompletedEventHandler(object sender, SubmitNonNumericDataBatchCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SubmitNonNumericDataBatchCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SubmitNonNumericDataBatchCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Guid Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Guid)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetBatchStatusCompletedEventHandler(object sender, GetBatchStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetBatchStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetBatchStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BatchStatus Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BatchStatus)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetBatchStatusesByDateRangeCompletedEventHandler(object sender, GetBatchStatusesByDateRangeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetBatchStatusesByDateRangeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetBatchStatusesByDateRangeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BatchStatus[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BatchStatus[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetInvalidBatchDataCompletedEventHandler(object sender, GetInvalidBatchDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetInvalidBatchDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetInvalidBatchDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public InvalidBatchData[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((InvalidBatchData[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void DeleteNumericDataCompletedEventHandler(object sender, DeleteNumericDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteNumericDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteNumericDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Guid Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Guid)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591